version: 0.0.1
boundedContextName: app-health
moduleName: application-authentication
moduleNames: application-authentications
aggregateName: AppHealthApplicationAuthentication
hasOAuth: false
hasTenant: false
hasAuditing: false
aggregateProperties:
  - name: id
    type: id
    primaryKey: true
    length: 36
    nullable: false
  - name: applicationId
    type: id
    length: 36
    nullable: false
    relationship:
      type: many-to-one
      aggregate: AppHealthApplication
      modulePath: app-health/application
      key: id
      field: application
      avoidConstraint: true
    webComponent:
      type: select
  - name: authenticationInterfaceId
    type: id
    length: 36
    nullable: false
    relationship:
      type: many-to-one
      aggregate: AppHealthAuthenticationInterface
      modulePath: app-health/authentication-interface
      key: id
      field: authenticationInterface
      avoidConstraint: true
    webComponent:
      type: select
  - name: totalUsers
    type: int.unsigned
    maxLength: 10
    nullable: true
  - name: score
    type: int.unsigned
    maxLength: 10
    nullable: false
  - name: applicationInfrastructureServiceId
    type: id
    length: 36
    nullable: false
    relationship:
      type: many-to-one
      aggregate: AppHealthApplicationInfrastructureService
      modulePath: app-health/application-infrastructure-service
      key: id
      field: applicationInfrastructureService
      avoidConstraint: true
    webComponent:
      type: select
  - name: createdAt
    type: timestamp
    nullable: true
  - name: updatedAt
    type: timestamp
    nullable: true
  - name: deletedAt
    type: timestamp
    nullable: true
aggregateI18nProperties: []
additionalApis: []
