version: 0.0.1
boundedContextName: app-health
moduleName: application-api
moduleNames: application-apis
aggregateName: AppHealthApplicationApi
hasOAuth: false
hasTenant: false
hasAuditing: false
aggregateProperties:
  - name: id
    type: id
    primaryKey: true
    length: 36
    nullable: false
  - name: applicationId
    type: id
    length: 36
    nullable: false
    relationship:
      type: many-to-one
      aggregate: AppHealthApplication
      modulePath: app-health/application
      key: id
      field: application
      avoidConstraint: true
    webComponent:
      type: select
  - name: apiInterfaceTypeId
    type: id
    length: 36
    nullable: false
    relationship:
      type: many-to-one
      aggregate: AppHealthApiInterfaceType
      modulePath: app-health/api-interface-type
      key: id
      field: apiInterfaceType
      avoidConstraint: true
    webComponent:
      type: select
  - name: score
    type: smallint.unsigned
    maxLength: 6
    nullable: false
  - name: documentations
    type: json
    nullable: true
  - name: requestsPerDay
    type: int.unsigned
    maxLength: 10
    nullable: true
  - name: applicationInfrastructureServiceId
    type: id
    length: 36
    nullable: false
    relationship:
      type: many-to-one
      aggregate: AppHealthApplicationInfrastructureService
      modulePath: app-health/application-infrastructure-service
      key: id
      field: applicationInfrastructureService
      avoidConstraint: true
    webComponent:
      type: select
  - name: createdAt
    type: timestamp
    nullable: true
  - name: updatedAt
    type: timestamp
    nullable: true
  - name: deletedAt
    type: timestamp
    nullable: true
aggregateI18nProperties: []
additionalApis: []
